### ISSUE TITLE
Spell

### ISSUE THREAD

**Issue by Stakanhay** [SAP-samples/btp-kyma-cap-multitenant-susaas#1]
#- ![image](https://user-images.githubusercontent.com/132062317/235128790-35812438-496a-4f2c-b1a8-cebca1d03985.jpeg)[_@_]()![image](https://user-images.githubusercontent.com/132062317/235129061-b203c62f-852b-4081-84e6-1c1c38ef1378.png)

**Comment by SebastianWolf-SAP** [comment]
Please refrain from such posts, they are violating our [code of conduct](https://github.com/SAP-samples/btp-kyma-cap-multitenant-susaas/blob/main/CODE_OF_CONDUCT.md). We will close this issue and block you for 7 days. Thank you for your understanding.
